name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: action-yarn
        uses: comchangs/action-yarn@v0.1-beta
        with:
          args: "yarn"
      - name: ESLint checks
        uses: hallee/eslint-action@1.0.1
