name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0
      - name: ESLint checks
        uses: stefanoeb/eslint-action@1.0.0
        with:
          args:  "../../src/**.js"
